//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<decimal> GIAGIAM { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public string ANHBIA { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.DateTime> NGAYSANXUAT { get; set; }
        public string NOISANXUAT { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public Nullable<int> MANCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
